# Generated by Django 6.0.3 on 2026-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0005_nutriuser_registered_by_nutriuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('general', 'General'), ('briefing', 'Morning Briefing')], default='general', max_length=20),
        ),
    ]
