# Generated by Django 6.0.3 on 2026-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0006_aiinsight_insight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='weight',
            field=models.FloatField(blank=True, help_text='Current weight in kg', null=True),
        ),
    ]
