# Generated by Django 6.0.3 on 2026-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0007_dailylog_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calcium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='glycemic_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='health_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_size_grams',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='preparation',
            field=models.TextField(blank=True, help_text='Traditional preparation methods', null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Average price', max_digits=10),
        ),
    ]
