# Generated by Django 6.0.3 on 2026-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0008_remove_fooditem_nutrition_fooditem_allergens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='muac_cm',
            field=models.FloatField(blank=True, help_text='Mid-Upper Arm Circumference in cm', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whz_score',
            field=models.FloatField(blank=True, help_text='Weight-for-Height Z-score', null=True),
        ),
    ]
