# Generated by Django 6.0.3 on 2026-03-07 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0009_userprofile_muac_cm_userprofile_whz_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=100)),
                ('clinical_notes', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('weight', models.FloatField(null=True)),
                ('muac_cm', models.FloatField(null=True)),
                ('whz_score', models.FloatField(null=True)),
                ('monitoring_freq', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
